### ISSUE TITLE
LOD Distance in X-Wing and TIE Fighter

### ISSUE THREAD

**Issue by bguthrie1** [rdoeffinger/xwa_ddraw_d3d11#12]
I think a threshold for the constant should be based on the CMD in TIE Fighter. LODs are quick to show up in the CMD which makes it look really bad.

**Comment by bguthrie1** [comment]
What it is now:

![image](https://user-images.githubusercontent.com/43460482/52144187-6ce93380-2612-11e9-8435-09bf6be04b26.png)

What it should be:

![image](https://user-images.githubusercontent.com/43460482/52144230-96a25a80-2612-11e9-8fc1-9f1bfb27a56d.png)

**Comment by rdoeffinger** [comment]
[ddraw-lod.zip](https://github.com/rdoeffinger/xwa_ddraw_d3d11/files/2823301/ddraw-lod.zip)
Please test

**Comment by bguthrie1** [comment]
Works great!
