### ISSUE TITLE
Joystick Option Request

### ISSUE THREAD

**Issue by r2rangel** [rdoeffinger/xwa_ddraw_d3d11#14]
I noticed from the last time i used it, you've added a throttle switch option on ddraw.cfg to switch from the annoying right analog to the triggers on xinput controllers (awesome actually, Thanks), and I have a request if would be possible, to assign the throttle to null input ? or off ? I use steam controller profile, and I find that the throttle option is rather useless to have, if you are either full stop or full throttle most of the time, or matching speeds, i rather give up 3 functions on my controller, since i use the triggers mostly to change action layers. Thanks !

**Comment by rdoeffinger** [comment]
Hmm, I may have misunderstood, but... Doesn't the latest version already do that? You need to change the configuration if you want throttle control via trigger.

**Comment by r2rangel** [comment]
Yes, totally get it I'm actually using it as the triggers, but I think you misunderstood me, what I mean is to actually disable it, if you could change it from the right analog to the triggers, I'm guessing you could point it to something else like a null axis, so to be able to disable it completely right ? leaving the triggers and the right analog axis free for other bindings.

**Comment by rdoeffinger** [comment]
But disabled is the default now! Have you tried the latest version? And not changed ddraw.cfg?

**Comment by r2rangel** [comment]
Yeah, tried and was not working until I figured out and was my mistake sorry. My gamepad has 2 pairing options, either dinput or xinput, on dinput the XInputTriggerAsThrottle = 0 option does not disable the right analog throttle... go figure, changed to xinput and sure enough is working, thanks. sorry to bother about this, I guess i got confused because i red InputTriggerAsThrottle option, and tough the default option was off, as in disable the trigger throttle and use original horizontal right analog axis.
By the way, I´m using a 8Bitdo SN30 PRO GAMEPAD. thanks again, great work !

**Comment by rdoeffinger** [comment]
I have to admit I have no idea what happens in dinput mode (at least so far the ddraw.dll does not touch that behaviour at all), but since you found a solution I'll close it.
