### ISSUE TITLE
 "Direct3d texture load: parameter incorrect" Error when loading into mission.

### ISSUE THREAD

**Issue by bazrrrr** [rdoeffinger/xwa_ddraw_d3d11#23]
This error pops up whenever I load into a mission itself in XWA. I'm not the only one who's seen this. This error doesn't seem to occur in Jeremy's version.

**Comment by rdoeffinger** [comment]
Not sure it'll help, but can you say which graphics card that is and if you have the latest drivers installed?
I've not seen this issue or heard of someone having it before...

**Comment by bazrrrr** [comment]
Ok I just tried on an old cd install and it worked fine. Justagai's vanilla campaign co-op version seems to cause this so will have to check that install further.
