### ISSUE TITLE
xwing special edition [gog] (XWING95.EXE) ddraw downgrade video quality

### ISSUE THREAD

**Issue by luca2125** [rdoeffinger/xwa_ddraw_d3d11#25]
Hi,

I have tried to replace to apply this patch to xwing95.exe but the quality is it is worse than before (too much pixel effect).

I the past I have tried this patch with xvt and I get better result, but not with xwing95.exe.

In both casse I have set: ScalingType = 1 (smoother, alpha blended scaling).

I need to use this patch becouse convert old ddraw to ddraw 11 and allow me to record cutscene and work.

But not the pixels are more evident.

Thare is a way to solve ?

Thanks !

**Comment by rdoeffinger** [comment]
Which part of the game? The 2D and the 3D parts are fundamentally different.
You can set Width and Height to 640x480 (or change the desktop resolution to that) to get scaling from your graphics card/monitor, if you think that looks better. It will make the 3D parts look a lot worse though.

**Comment by luca2125** [comment]
Thank you I have solved the problem.
