### ISSUE TITLE
Direct3DTexture:Load error

### ISSUE THREAD

**Issue by DarthJahus** [rdoeffinger/xwa_ddraw_d3d11#27]
Getting Direct3DTextue:Load error "Incorrect parameter".

After closing the dialog window, the game is left in this state. No textures are loaded.

![image](https://user-images.githubusercontent.com/7353366/119356860-cde31c80-bc9e-11eb-9ee1-7c87cc38613a.png)

---

OS: Windows 10 21H1 (19043.906)
CPU: R5 3600X
GPU: RX 580 8 GB
AMD drivers: 21.4.1 (27.20.21002.112)

**Comment by DarthJahus** [comment]
Looks like it has to do with enabling Hardware MIP Maping from the game's Hardware Only Video Options. Works as expected, when MIP Maping is disabled.

**Comment by DarthJahus** [comment]
Looks like it has to do with enabling Hardware MIP Maping from the game's Hardware Only Video Options. Works as expected, when MIP Maping is disabled.

**Comment by rdoeffinger** [comment]
Hm, I think you really want mip-mapping enabled, so I don't think your workaround is a good idea.
Maybe it does not recognize that you are running XWA?
Try setting
XWAMode = 1
(i.e. change the -1 to 1) in ddraw.cfg
