### ISSUE TITLE
Bugged mipmap setting

### ISSUE THREAD

**Issue by purplerhino83** [rdoeffinger/xwa_ddraw_d3d11#28]
Setting "Hardware Mip Mapping" to anything above "off" in Hardware only video option ingame menu gives an error when trying to load a game. Ignoring that still loads the game but all the 3d objects become white and textureless.

![Untitled0](https://user-images.githubusercontent.com/89957191/131777642-046857bf-78b0-4282-b858-23df365159ab.png)
![Untitled1](https://user-images.githubusercontent.com/89957191/131777659-0e8f0c76-f5e6-4f26-97c1-4c45050d22a5.png)

**Comment by rdoeffinger** [comment]
I'll see if I can reproduce it in the coming days/weeks, but note that for XWA it might be better to use the upstream project https://github.com/JeremyAnsel/xwa_ddraw_d3d11
There's a good chance this is related to the code to add HW mipmapping to the older games (they do not support it originally), and thus an example that it can be tricky to support all games of the series with one code base.

**Comment by purplerhino83** [comment]
I tried Jeremy's version right after getting this bug. The game wouldn't even start with that version and i assumed that's due to that one being only compatible with Upgrade Pack. I messed around with the ini by changing some values and disabling some stuff but it still wouldn't start.

**Comment by rdoeffinger** [comment]
Good news: I could reproduce your issues.
Bad news: I don't understand what is going wrong. This will not be a quick fix, so might not have a fix anytime soon.

The strange thing is, it works fine in the upstream JeremyAnsel code, but it seems not related to any of my changes in the area...
Try setting
Text2DRendererEnabled = 0
Radar2DRendererEnabled = 0
in his ddraw.cfg to see if it works for you. I think his binary patching code is not quite careful enough and causes hangs on startup, I don't think his version requires the upgrade pack (works on my install without).

**Comment by rdoeffinger** [comment]
Ok, it was much more stupid than thought.
Don't have my signing key with me so a proper release will have to wait a month or 2, but if you don't mind an unsigned binary, here's a build:
[ddraw.zip](https://github.com/rdoeffinger/xwa_ddraw_d3d11/files/7129079/ddraw.zip)

**Comment by purplerhino83** [comment]
Woah that was fast. I'll check soon and also try your method with Jeremy's version. Will let you know.

**Comment by Danfun64** [comment]
Any chance of a signed binary coming out soon? It's been more than a couple months now...

**Comment by rdoeffinger** [comment]
I made a new release now, please test since I admit I didn't really this time, too many other things to do.
