### ISSUE TITLE
InvertYAxis should be set to 1 and JoystickEmul should be set to 0 by default

### ISSUE THREAD

**Issue by bguthrie1** [rdoeffinger/xwa_ddraw_d3d11#6]
My issue is that my Y axis was not inverted. Pulling on the stick should pitch the craft up. I did not have this issue with the previous ddraw versions. Other people had this issue as well.

I believe I also recall an issue with someone who had to force the joystick emulation to off as it was messing with his physical joystick.

For those who do need Joystick emulation support, they can turn it on manually in the config, but most people will be using a joystick or controller of some sort so this should be set to off by default.

EDIT: It might be ok with JoystickEmul to -1 as default, but the InvertYAxis definitely should be set to 1.

**Comment by bguthrie1** [comment]
Hello, I apologize if I was a little demanding. The motivation to having this fixed is so that I can redirect those in my discord directly to your github and download the latest version without issues. We generally help troubleshoot those who are having issues with the ddraw and some of those issues are related to the ones I mentioned in the first post. Since we have a majority of users that use a joystick/controller for this game, it made the most sense to me that the y inversion would be like the original game. I do however see the use in having the joystick emulation set to -1 as I have made great use with it in the past for testing. I'll try to find out if there are any issues with the auto detection.

**Comment by rdoeffinger** [comment]
I think we have no disagreement on the "it should just work" and "pulling the joystick should turn the ship upwards".
It's just that our facts don't seem to agree, and we will need to find out why.
The facts I believe to have are (though there might be bugs or misunderstandings):
- Connecting my ThrustMaster joystick, pulling does turn upwards with InvertYAxis set to 0. Setting it to 1 would actually cause it to behave wrong
- I added InvertYAxis because some GamePads have an inverted Y axis when they emulate a joystick and no way to configure that
- With JoystickEmul set to 0 (or otherwise disabling XInput support) there is no simple way I know of to distinguish these cases, so one or the other would not work without manual configuration.

Now what makes me suspicious however is that you say you did not have this issue in older versions, this is unexpected and might indicate the issue you are seeing might actually be a bug somewhere, as JoystickEmul = 0 and InvertYAxis = 0 is supposed to show EXACTLY the same behaviour as with old versions of the dll that had no joystick emulation at all.
So we'll need to dig a bit deeper into why things go wrong.
Btw. one thing to check is that the Y axis inversion setting in XWA itself wasn't changed by accident...

**Comment by bguthrie1** [comment]
![image](https://user-images.githubusercontent.com/43460482/50712197-75efe080-1025-11e9-8f55-3e15f7ed3096.png)

Those are my settings in game.

If I restore the defaults this is what happens:

![image](https://user-images.githubusercontent.com/43460482/50712237-991a9000-1025-11e9-8fd3-f1a412434065.png)

I wanted to confirm that the default option for the y axis was set to "No". 

Something is odd here but I'm not sure what

**Comment by rdoeffinger** [comment]
To my knowledge DirectInput is not involved here at all.
XWA uses the old winmm.dll joystick methods, specifically joyGetPosEx.
So it might be the winmm.dll? And maybe my ddraw.dll picks up a different winmm.dll from what XWINGALLIANCE.EXE picks somehow?

**Comment by bguthrie1** [comment]
I've sent you a private message on what I've found on the XWAUP forums. I've also noticed reWASD (https://www.rewasd.com/) seems to be having issues hooking onto my controller with JoystickEmul at -1.

I use win32.dll instead of winmm.dll, but I've tried both (and removed them both to use the system winmm.dll) but the result is the same. My y axis for the controller is automatically inverted somehow so the ddraw would "revert" it to normal and mess up gameplay.

**Comment by rdoeffinger** [comment]
The reWASD homepage seem to provide no information on how they hook into thing. JoystickEmul -1 should result in it auto-detecting JoystickEmul 2, which in turn means simple polling via XInputGetState, which is provided by XInput9_1_0.dll, is used. It will always use controller 0, probably should make sure things are configured such that that's not the real controller.
Of course with that many programs involved it gets rather hard to say where the issue is, and which component is doing what...

**Comment by bguthrie1** [comment]
I had reWASD turned off and its the same thing. Something else seems to be causing the issue.

**Comment by bguthrie1** [comment]
Ok I've found the issue. I've looked through the ddraw source code and found this. 

```C
if (g_config.JoystickEmul == 2) {
		XINPUT_STATE state;
		XInputGetState(0, &state);
		pji->dwFlags = JOY_RETURNALL;
		pji->dwXpos = state.Gamepad.sThumbLX + 32768;
		pji->dwYpos = state.Gamepad.sThumbLY + 32768;
		if (g_config.InvertYAxis) pji->dwYpos = 65536 - pji->dwYpos;
		// The 65536 value breaks XWA with in-game invert Y axis option
		pji->dwYpos = std::min(pji->dwYpos, DWORD(65535));
		pji->dwZpos = state.Gamepad.bRightTrigger;
		pji->dwRpos = state.Gamepad.sThumbRX + 32768;
		pji->dwUpos = state.Gamepad.sThumbRY + 32768;
		pji->dwVpos = state.Gamepad.bLeftTrigger;
		pji->dwButtons = 0;
		// Triggers first
		if (state.Gamepad.bLeftTrigger > XINPUT_GAMEPAD_TRIGGER_THRESHOLD) pji->dwButtons |= 1;
		if (state.Gamepad.bRightTrigger > XINPUT_GAMEPAD_TRIGGER_THRESHOLD) pji->dwButtons |= 2;
		// Thumb and shoulder buttons next
		pji->dwButtons |= (state.Gamepad.wButtons & 0x3c0) >> 4;
		// A, B, X, Y
		pji->dwButtons |= (state.Gamepad.wButtons & 0xf000) >> 6;
		// start and back
		pji->dwButtons |= (state.Gamepad.wButtons & 0x30) << 6;
		// XWA can map only 12 buttons, so map dpad to POV
		pji->dwPOV = povmap[state.Gamepad.wButtons & 15];
```

For some reason this was executing even with JoystickEmul = -1

Here is why:

```C
static int needsJoyEmul()
{
	XINPUT_STATE state;
	if (XInputGetState(0, &state) == ERROR_SUCCESS) return 2;
	UINT cnt = joyGetNumDevs();
	for (unsigned i = 0; i < cnt; ++i)
	{
		JOYINFOEX jie;
		memset(&jie, 0, sizeof(jie));
		jie.dwSize = sizeof(jie);
		jie.dwFlags = JOY_RETURNALL;
		UINT res = joyGetPosEx(0, &jie);
		if (res == JOYERR_NOERROR)
			return 0;
	}
	return 1;
}
```

```C
if (XInputGetState(0, &state) == ERROR_SUCCESS) return 2;
```

This will return successful for Xbox Controllers. 

I'll have to think on how to approach this.

**Comment by rdoeffinger** [comment]
Yes, I know that code, and I said it uses XInput when set to -1 (because otherwise many gamepads are not really usable unless using XInput, of course that can be worked around with something like rewasd, but that's not a "just works" solution when you have to tell people to buy something first).
But that doesn't explain why InvertYAxis should be set to 1 even when JoystickEmul is 0, as per topic of this issue.

**Comment by bguthrie1** [comment]
I apologize I have just noticed your message stating that. 

I've been rereading your posts and I see I have been missing a lot of information. So I would like to address these.

```
Connecting my ThrustMaster joystick, pulling does turn upwards with InvertYAxis set to 0. Setting it to 1 would actually cause it to behave wrong
```
This makes sense if the ThrustMaster was not returning any Dinput state. If my Xbox Controller didn't return JoystickEmul = 2, there wouldn't be an a y-axis issue in which it would act like the ddraws before. This isolates the issue to the Xinput code in the ddraw. If there was code detecting Xinput devices in the previous ddraws (like around 1.5.1) then I am wrong and something else is clearly the problem.

```
I added InvertYAxis because some GamePads have an inverted Y axis when they emulate a joystick and no way to configure that
```
I'm curious, which gamepads have this issue?

```
With JoystickEmul set to 0 (or otherwise disabling XInput support) there is no simple way I know of to distinguish these cases, so one or the other would not work without manual configuration.
```

I fear that with certain controllers that there will have to be some manual configuration due to the way they are setup. Speaking of certain controllers…I've noticed that in the ddraw config for JoystickEmul = 2 states: 

```
; Force XInput to use a special XInput mode that is adjusted to what worked
; best for my experiments with a Steam controller, so it might not be useful
; for anyone else.
```

I'm going to assume based on the text here that this solution came about to allow the Steam controller to just work. Creating a solution around the Steam controller can be problematic due to the fact that it has so much customization. I have a steam controller myself and I have in the past ran many tests to get the perfect config for the xwing series. Due to it being so problematic and that its so integrated with Steam, I gave up and decided to go with reWASD for the solution. 

I ran some quick tests with a Steam Controller on a default desktop configuration (base configuration) with the ddraw to see how the y axis is set by default, but its difficult to tell due to the many configurations it has. I tried applying my old config to the steam controller and noticed that they removed (?) "Joystick Move" as an input option.

I still think that you are on the right path here to allowing all controllers to just work. Your ddraw would allow those with a Steam controller to just work with XWA without having a hard connection to Steam itself which I wish I had back then as this was the problem that was frustrating me most. I believe the best solution here is to separate the Steam Controller from the other Dinput devices in the ddraw due to the sheer amount of customization it offers. Though I'm not sure how to differentiate a Steam Controller from other devices through Xinput which may be the difficult part.

Would you be able to send me your Steam Controller configuration? I'm curious as to what you use and I would like to run some tests. Also does the y axis issue also occur with an Xbox controller on your end?

**Comment by rdoeffinger** [comment]
I can't answer your first questions, much of the issues I heard about were not detailed or second-hand, and I do not own any normal controller to test myself, so your input is quite welcome.

I uploaded my Steam Controller configuration as "XWA with gyro". But note that using it is painful: XInput emulation (and thus most of the configuration options) for Steam Controller does not work when they start the launcher first, you have to save the configuration to a local template, then create a shortcut to XWINGALLIANCE.EXE, apply the template configuration saved earlier and then run it via the shortcut. Also note that you'll almost definitely want to change the button bindings in-game, especially "button 2" to "None".

For the Steam controller I have no particular preference on which way around the Y axis is to be honest. My point was just that if controllers have the Y axis the wrong way round, it's because they report it so. Or maybe it's that Microsoft defined the Y axis flipped for the XInput API?
I'm fine with changing the XInput-specific piece of code to flip the meaning of InvertYAxis, i.e. from
		if (g_config.InvertYAxis) pji->dwYpos = 65536 - pji->dwYpos;
to
		if (!g_config.InvertYAxis) pji->dwYpos = 65536 - pji->dwYpos;
if you think that will improve things, though it would be nice if it could be tested with a couple of gamepads (e.g. Xbox and PS4 or so?)!

**Comment by bguthrie1** [comment]
I'll take a look at the Steam controller config sometime. It does sound like I would be sticking with my reWASD setup though.

Just want to iterate something for my own understanding (more of a theory): Microsoft seems to have Xinput controllers (or just the Xbox controller, not sure) have their y axis inverted by default. But for some reason if the y axis was overriden using the joyinfoex structure it reverts to normal. Somewhere in Windows its forcing a y axis inversion on the controller unless its overridden. 

Perhaps this was a way to allow old games to simply work with the controller since most of the time the y axis was expected to be y inverted for these old games? Newer developers would just override the axis and buttons anyway, so they would never deal with the issue. 

As for inverting the y axis, the problem I realized is that the overriding of buttons through Xinput messes up my reWASD setup for some odd reason. Granted not everyone will be using reWASD, so I don't think its something to prioritize around but it is something to keep in mind. 

This is a toughie. The best solution for myself would be to set "JoystickEmul = 0" in the config. For a majority of people, they will be using joysticks and xbox controllers. Flipping the y axis for Xinput like you said would fix the issue for Xbox Controllers, though I'm not sure about the buttons. More testing will be needed here and I will let you know how the buttons respond.

**Comment by bguthrie1** [comment]
Confirmed that there is an issue with the buttons. The ddraw seems to limit the amount of buttons to like 5 or 6.

**Comment by rdoeffinger** [comment]
See the comments in the code, it maps 12 buttons plus dpad:
// Triggers first
 if (state.Gamepad.bLeftTrigger > XINPUT_GAMEPAD_TRIGGER_THRESHOLD) pji->dwButtons |= 1; 
if (state.Gamepad.bRightTrigger > XINPUT_GAMEPAD_TRIGGER_THRESHOLD) pji->dwButtons |= 2;
 // Thumb and shoulder buttons next 
pji->dwButtons |= (state.Gamepad.wButtons & 0x3c0) >> 4;
 // A, B, X, Y 
pji->dwButtons |= (state.Gamepad.wButtons & 0xf000) >> 6;
 // start and back 
pji->dwButtons |= (state.Gamepad.wButtons & 0x30) << 6;
 // XWA can map only 12 buttons, so map dpad to POV 
pji->dwPOV = povmap[state.Gamepad.wButtons & 15];

**Comment by rdoeffinger** [comment]
According to https://docs.microsoft.com/en-us/windows/desktop/api/xinput/ns-xinput-_xinput_gamepad that actually maps all buttons the XInput interface defines.

**Comment by bguthrie1** [comment]
That's strange then...the buttons are not only limited but they are completely different from before. Several buttons that I've bound on my Xbox Controller through XWA are not binding correctly.

**Comment by bguthrie1** [comment]
By default, the buttons on the Xbox Controller are bound as follows:

A = Button 1
B = Button 2
X = Button 3
Y = Button 4
Left Bumper = Button 5
Right bumper = Button 6
Select or the Left menu button = Button 7
Start or the right menu button = Button 8
Joystick Left Press = Button 9
Joystick Right Press = Button 10
Then the POV buttons. 

If JoystickEmul = -1 (which is set to 2 in the code)

A = Button 7
B = Button 8
X = Button 9
Y = Button 10
Left Bumper = Button 5
Right Bumper = Button 6
Select or the Left menu button = Button 12
Start or the right menu button = Button 11
Left Stick Press = Button 3
Right Stick Press = Button 4

Addtionals:
Left Trigger = Button 1
Right Trigger = Button 2

I will say having the triggers remappable is pretty cool, but it looks like the buttons are set out of order with the code above.

**Comment by bguthrie1** [comment]
This code will set the buttons to that of the Xbox controller.

```C
                // shoulder buttons next
		pji->dwButtons |= (state.Gamepad.wButtons & 0x300) >> 4;
		// Thumb buttons
		pji->dwButtons |= (state.Gamepad.wButtons & 0xc0) << 2;
		// A, B, X, Y
		pji->dwButtons |= (state.Gamepad.wButtons & 0xf000) >> 12;
		// start and back
		pji->dwButtons |= (state.Gamepad.wButtons & 0x10) << 3;
		pji->dwButtons |= (state.Gamepad.wButtons & 0x20) << 1;
```C

**Comment by rdoeffinger** [comment]
We can't avoid disrupting the standard when the standard is broken and plain doesn't work. Sure, could have different setup for XWA vs. the other games but that still would be confusing in other ways.
Also how about people who do NOT have a setup already? Having the A button as fire button and the trigger button all the way down doesn't seem great even for XWA then.

**Comment by bguthrie1** [comment]
The standard is fine honestly. If you start remapping buttons you're going to get people asking why they only have 5 or 6 buttons or why their controller doesn't work. If people don't have a setup, then the expectation is that they won't change anything in their config anyway. 

If you don't want the A button to be the fire button, you simply remap it in XWA. Same thing for the trigger. I really don't see the issue here.

**Comment by rdoeffinger** [comment]
Need to check the other games how many buttons they support, but maybe putting the triggers at 8 and 9 might be a compromise.
But in the end trying to be 100% compatible with the emulation just results in something just as bad as the emulation, and that you can get by just disabling the XInput support...

**Comment by bguthrie1** [comment]
The other games support 12 buttons.

Heck, the games actually support 20 buttons. Minus 4 for the POV. 

If we are going to remap buttons at the hardware level, then we might as well remove the Xinput support because it would cause too much trouble.

**Comment by rdoeffinger** [comment]
Oh, it's XWA that supports fewest buttons?
I've been trying to think why I've done it this way. I think the reason is that I assumed that the trigger would be the "normal" fire button.
And the other buttons are in the order of the XInput structure.
If I can't think of a better reason for how I did things I might actually agree with you...
I was mostly considering people who start the game for the first time, and for that I still like my mapping a bit better, but I see that it's very confusing for people starting with an existing setup (note that based on the Steam controller I also had the impression that without XInput support gamepads would not be usable anyway).

**Comment by bguthrie1** [comment]
Sorry when I said "games" I meant all of the games in the series. 

In the config for XvT or XWA:

![image](https://user-images.githubusercontent.com/43460482/51524136-36294700-1de2-11e9-8957-3b10f0521193.png)

Only 12 buttons are shown in game, but you can edit 20 buttons in the config. X-Wing and TIE Fighter probably support the same but since their configs are encoded, one would have to edit it by a hex editor. But the idea is still possible.

The Xbox controller by default probably had this weird default structure to support old games right off the bat. Of course getting it to work "out of the box" will be different to everyone and unfortunately this could cause issues. So this weird standard has to be followed or else people with established configs are going to wonder why the game doesn't respond to their controller.

I too have my trigger button as the fire button. Set through reWASD of course. By having the trigger buttons as 11 and 12, the original standard is kept and I can remap A button to something else other than fire, and remap the trigger button to fire.

**Comment by rdoeffinger** [comment]
You are right, I was wrong. Sorry for my stubbornness and thanks for insisting long enough to overcome it

**Comment by bguthrie1** [comment]
No problem, I've dealt with worse believe me :P. I still think Xinput support is a great idea since people won't have to buy reWASD to remap their triggers. 

Although something has been on my mind lately: http://www.xwaupgrade.com/phpBB3/viewtopic.php?p=156769#p156769

I'm wondering if this dude from the post was replacing the ddraw after an XWAUP installation. The symptoms he describes are similar to what I experienced just now. Makes me wonder if a T.Flight HOTAS is sending an Xinput state...but I'm not sure. I've posted a note to see if he was changing the ddraw. 

Anyway, I'm glad to have gotten this all covered. I'm all for the betterment of the game and for the users experience so I'm glad to have been a part of this.

**Comment by rdoeffinger** [comment]
I think I need to change the code to only use XInput if there is no joystick or it is an emulated one.
Any chance you could write a program to call joyGetDevCaps and report szPname and szOEMVxD for some of your devices like the xbox controller?
Seems like the best chance to figure out whether to use XInput or not.
Well, or maybe just pick whichever has more axis? Or only pick the joystick if it has at least 3 axis? Any other idea?

**Comment by bguthrie1** [comment]
I'll def look into it. I'll let you know what I come up with.

**Comment by bguthrie1** [comment]
I would have thought that the driver OEM support would be from the company who made the drivers, but its possible they could just use Microsoft's drivers for Xinput support so you're right. I'll have to think of another way.

**Comment by bguthrie1** [comment]
szPname might be the way to go. I'll have to check and see what name is returning with the Xbox controller and we can use that. The only issue I can think of with this is if there is some way to change the name of the controller.

**Comment by bguthrie1** [comment]
There may be an easy way of detecting an Xbox controller using the Xinput API.

https://docs.microsoft.com/en-us/windows/desktop/api/xinput/nf-xinput-xinputgetcapabilities

With the XINPUT_FLAG_GAMEPAD flag it will "Limit query to devices of Xbox 360 Controller type.". So this should only detect 360 (it should detect the One as well, I have a one so I can see to that) controllers.

**Comment by rdoeffinger** [comment]
I am very wary of this flag. Any controller that wants to actually work for programs designed for Xbox controllers will have to pretened to be a xbox 360 controller. Vice versa, some actual gamepads might not be found this way. It seems unfortunately fairly likely to me that this flag will not have correlation with anything interesting.
Also even if it worked I don't think it's quite what we want. Because if someone has a proper joystick connected as well, they probably way to play XWA using that, not the gamepad.
Thus I would think it would be more useful to have a joystick blacklist rather than an XInput whitelist.
As for the Steam controller, unfortunately it seems to report a generic Microsoft driver via the joystick API, the only way to detect it seems to be to look for wMid == 0x45e and wPid == 0x28e

**Comment by bguthrie1** [comment]
The triggers aren't detected as buttons with your posted code.

I understand where you are coming from but I still think we should use the "XINPUT_FLAG_GAMEPAD" flag as a...how to say it...a backup? It's just one of many checks to ensure that we are getting is true. It wouldn't be the sole check for detecting a device.

I'll still check the szPname string and see what its returning with my controller though. That will definitely be a sure fire way of detecting an Xbox controller.

**Comment by bguthrie1** [comment]
Unfortunately my C++ skills are below par...What would be the code to output szPname?

**Comment by rdoeffinger** [comment]
I don't really see how it would be possible to use XINPUT_FLAG_GAMEPAD "as a backup", at least not if the goal is for the solution to work when both a joystick and a gamepad are connected.
Below code prints a couple of things (if it doesn't compile you might have to remove/replace the sleep() call).

#include <windows.h>
#include <mmsystem.h>
#include <stdio.h>
int main()
{
JOYCAPS caps;
joyGetDevCaps(0, &caps, sizeof(caps));
printf("%i %x mid:%x pid:%x %s %s %s\n", caps.wNumAxes, caps.wCaps, caps.wMid, caps.wPid, caps.szPname, caps.szRegKey, caps.szOEMVxD);
sleep(100);
}

**Comment by bguthrie1** [comment]
Hmm yeah I can't seem to compile this at all. I've removed the sleep function and it wanted me to add "#include "pch.h" so I included it. Now it is throwing an error:

Error	C2146	syntax error: missing ';' before identifier 'caps'	OutputDeviceName	c:\users\bguth\source\repos\outputdevicename\outputdevicename\outputdevicename.cpp	10	

I created this as a console app by the way. This is the code so far:

```C
#include <windows.h>
#include <mmsystem.h>
#include <stdio.h>
#include "pch.h"
int main()
{
	JOYCAPS caps;
	joyGetDevCaps(0, &caps, sizeof(caps));
	printf("%i %x mid:%x pid:%x %s %s %s\n", caps.wNumAxes, caps.wCaps, caps.wMid, caps.wPid, caps.szPname, caps.szRegKey, caps.szOEMVxD);
	//sleep(100);
}
```

**Comment by bguthrie1** [comment]
I do know that the Xbox controller supports WinMM, DirectInput and Xinput and will adapt accordingly but I would have thought it would output a different ID...interesting.

**Comment by rdoeffinger** [comment]
[ddraw.zip](https://github.com/rdoeffinger/xwa_ddraw_d3d11/files/2784866/ddraw.zip)
Here's a version with just a check for wMid == 0x45e, maybe that works for detecting gamepads...

**Comment by bguthrie1** [comment]
Seems to detect my controller and the triggers are mapped to 11 and 12 buttons. 

Though I wonder if a joystick can somehow return wMid == 0x45e. It looks like its just the generic joystick driver so that seems possible....

**Comment by rdoeffinger** [comment]
wMid is the "manufacturer ID", so it's not an information about the driver but the device itself.
It certainly would be possible for a joystick to have the same "manufacturer", but I think there is a good chance that won't be the case.
Unfortunately that ID does not seem officially registered, so it's hard to say more on it.

**Comment by bguthrie1** [comment]
Hmm...I don't like to leave things to chance honestly. I wonder if there is another way to approach this situation...

My brain is a bit a foggy as of now so I won't be able to think of any solutions for the time being. I will think about it later.

**Comment by bguthrie1** [comment]
I've gotten some data from other folks on what their inputs are, though it is not a large sample size but it is a small idea of what we are dealing with:
```
joyID:0 | axes:5 | caps:37 | mid:45e | pid:28e | name:Microsoft PC-joystick driver | RegKey:DINPUT.DLL | OEMVxD:
joyID:1 | axes:4 | caps:33 | mid:44f | pid:b106 | name:Microsoft PC-joystick driver | RegKey:DINPUT.DLL | OEMVxD:

Device 0: PS3 controller as Xbox 360 controller
Device 1: Thrustmaster T-Flight Stick XBox
```

```
joyID:0 | axes:4 | caps:33 | mid:44f | pid:b10a | name:Microsoft PC-joystick driver | RegKey:DINPUT.DLL | OEMVxD:
joyID:1 | axes:0 | caps:0 | mid:0 | pid:0 | name: | RegKey: | OEMVxD:
joyID:2 | axes:6 | caps:3f | mid:44f | pid:b687 | name:Microsoft PC-joystick driver | RegKey:DINPUT.DLL | OEMVxD:

Device 0: Thrustmaster T1600M
Device 2: Thrustmaster TWCS Throttle
```
```
joyID:0 | axes:0 | caps:0 | mid:738 | pid:2221 | name:Microsoft PC-joystick driver | RegKey:DINPUT.DLL | OEMVxD:
joyID:1 | axes:0 | caps:0 | mid:738 | pid:a221 | name:Microsoft PC-joystick driver | RegKey:DINPUT.DLL | OEMVxD:
joyID:2 | axes:4 | caps:33 | mid:79 | pid:6 | name:Microsoft PC-joystick driver | RegKey:DINPUT.DLL | OEMVxD:
joyID:3 | axes:5 | caps:3e | mid:738 | pid:2221 | name:Microsoft PC-joystick driver | RegKey:DINPUT.DLL | OEMVxD:
joyID:4 | axes:0 | caps:0 | mid:0 | pid:0 | name: | RegKey: | OEMVxD:
joyID:5 | axes:0 | caps:0 | mid:0 | pid:0 | name: | RegKey: | OEMVxD:
joyID:6 | axes:0 | caps:0 | mid:0 | pid:0 | name: | RegKey: | OEMVxD:
joyID:7 | axes:0 | caps:0 | mid:0 | pid:0 | name: | RegKey: | OEMVxD:
joyID:8 | axes:0 | caps:0 | mid:0 | pid:0 | name: | RegKey: | OEMVxD:
joyID:9 | axes:0 | caps:0 | mid:0 | pid:0 | name: | RegKey: | OEMVxD:
joyID:10 | axes:0 | caps:0 | mid:0 | pid:0 | name: | RegKey: | OEMVxD:
joyID:11 | axes:0 | caps:0 | mid:0 | pid:0 | name: | RegKey: | OEMVxD:
joyID:12 | axes:0 | caps:0 | mid:0 | pid:0 | name: | RegKey: | OEMVxD:
joyID:13 | axes:0 | caps:0 | mid:0 | pid:0 | name: | RegKey: | OEMVxD:
joyID:14 | axes:0 | caps:0 | mid:0 | pid:0 | name: | RegKey: | OEMVxD:
joyID:15 | axes:0 | caps:0 | mid:0 | pid:0 | name: | RegKey: | OEMVxD:


Device 0: X56Pro Joystick
Device 1: Generic Joystick
Device 2: Generic Gamepad
Device 3: X56Pro Throttle
```

Note that the gamepad listed above has an mid of "79"

The following is a more extreme example:

![unknown2](https://user-images.githubusercontent.com/43460482/51725606-18452780-2018-11e9-9952-10843311cf76.png)

![unknown3](https://user-images.githubusercontent.com/43460482/51725628-4aef2000-2018-11e9-9d92-ae9719495c3a.png)

![unknown4](https://user-images.githubusercontent.com/43460482/51725631-4f1b3d80-2018-11e9-8402-5dd26264f5f7.png)

![unknown5](https://user-images.githubusercontent.com/43460482/51725632-52aec480-2018-11e9-9eb8-0fbe98c39b9c.png)

(In no order)
Thrustmaster Warthog Stick
Thrustmaster Cougar MFDs (x2)
RealSimulator FSSB R3 Lighting
Realsimulator TUSBA R2 (Thrustmaster Cougar USB Conversion device)
Saitek X52 Pro
mmjoy2 device
vjoy virtual device
Roccat Kone control device (part of the mouse software)

Another issue I've been dealing with is that the Xbox triggers (particularly the right trigger) is mapped to the z axis. This issue still occurs with the ddraw posted above. A lot of applications have trouble remapping the xbox controller buttons (particularly the triggers) and it takes a few specialized programs (such as reWASD or Steam) to remap them. But it seems that the left trigger was mapped to fire without messing with the z axis with the above ddraw so maybe it is possible. 

There is also something that I've read from the creator of a unity plugin called "rewired" that allows input from many different types of devices:

From the Rewired FAQ:
```


Can you/I add support for this controller?

It depends. Not all controllers are candidates for Rewired's automatic controller recognition system. The controller would have to be evaulated for inclusion.

Rewired's controller recognition system relies on information returned by the controller in order to be able to recognize it and load a hardware definition. Many times, the identifying information provided by the device is inadequate or too generic to be relied upon for recognition, for example those that show up as "Generic USB Joystick", "USB Gamepad", etc. This is true of a huge number of generic PC gamepads. The manufacturers of these gamepads create dozens and dozens of different products under a large variety of brands, some even with different button layouts, yet all of these devices provide exactly the same identifying USB/HID information (both product name and VID/PID). This makes it impossible to auto-recognize these controllers. If you were to add a controller definition for just one of these controllers, all others that don't match the button layout exactly would report incorrect element names and default mappings in the best case, and would be essentially unusable in the worst case. For these controllers, the only solution is to not provide a controller definition so that they will be treated as Unknown Controller which the user can map manually using Control Mapper or your own custom control remapping system.
The solution to allowing users to use these kinds of controllers and others without definitions is to give your players a way to remap their controls. It is a must that you have a system to let your player remap their controllers so they can use any controller they want. It is a core feature of Rewired to allow users to be able to use any controller regardless of whether or not it is recognized, including the ability to save and load their configurations. The controller recognition system is only really there as a convenience so that the most common controllers work without manual configuration out of the box, but it is not a substitute for being able to map controllers.
```

I think there is no question that eventually there can be some kind of system to attempt to detect and adapt to many devices in the ddraw. The question is, how much time do we want to divert to this task? This isn't going to be simple. This will take some serious hard work to do so. I think it would be better to leave the Xinput detection as an experimental option rather than forcing it on certain controllers. Simply because it is impossible to detect all the types of controllers/gamepads out there. Unfortunately we can't just have any device work out of the box. That's the just the nature of supporting many devices. I think folks that have devices that are really customizable or outliers such as the Steam Controller will naturally want to customize their input anyway and will be looking in the ddraw.cfg to customize. So it's better to just have Xinput detection set as an option.

**Comment by bguthrie1** [comment]
Basically, I think the best thing to do is to have JoystickEmul set to "0" by default. People who want to use a mouse or a different control scheme can customize it in the ddraw.cfg.

**Comment by rdoeffinger** [comment]
There is no "messing with the Z axis", I just find those games to be really painful to play without throttle, so I mapped the right trigger to throttle.

**Comment by bguthrie1** [comment]
Why wasn't that listed? I thought that was a bug. Well it's still a bug since even mapping the right trigger in game as something else seems to still keep it as throttle (as well as fire whatever was mapped to the right trigger in game).

**Comment by bguthrie1** [comment]
I apologize if I seem forceful. I get direct feedback from users with their input issues from this ddraw so I feel the full weight of the issue. 

 Here is my recommendation:

```C
if (g_config.JoystickEmul == 2) {
		XINPUT_STATE state;
		XInputGetState(0, &state);
		pji->dwFlags = JOY_RETURNALL;
		pji->dwXpos = state.Gamepad.sThumbLX + 32768;
		pji->dwYpos = state.Gamepad.sThumbLY + 32768;
		if (g_config.InvertYAxis) pji->dwYpos = 65536 - pji->dwYpos;
		// The 65536 value breaks XWA with in-game invert Y axis option
		pji->dwYpos = std::min(pji->dwYpos, DWORD(65535));
		//pji->dwZpos = state.Gamepad.bRightTrigger;
		pji->dwRpos = state.Gamepad.sThumbRX + 32768;
		pji->dwUpos = state.Gamepad.sThumbRY + 32768;
		//pji->dwVpos = state.Gamepad.bLeftTrigger;
		pji->dwButtons = 0;
		// Order matches XBox One controller joystick emulation default
// A, B, X, Y first
		pji->dwButtons |= (state.Gamepad.wButtons & 0xf000) >> 12;
		// Shoulder buttons next
		pji->dwButtons |= (state.Gamepad.wButtons & 0x300) >> 4;
		// start and back, for some reason in flipped order compared to XINPUT
		pji->dwButtons |= (state.Gamepad.wButtons & 0x10) << 3;
		pji->dwButtons |= (state.Gamepad.wButtons & 0x20) << 1;
		// Thumb buttons
		pji->dwButtons |= (state.Gamepad.wButtons & 0xc0) << 2;
		// Triggers last, they are not mapped in the joystick emulation
		if (state.Gamepad.bLeftTrigger > XINPUT_GAMEPAD_TRIGGER_THRESHOLD) pji->dwButtons |= 0x400;
		if (state.Gamepad.bRightTrigger > XINPUT_GAMEPAD_TRIGGER_THRESHOLD) pji->dwButtons |= 0x800;
		// These are not defined by XINPUT, and can't be remapped by the
		// XWA user interface as they will be buttons above 12, but map them just in case
		pji->dwButtons |= (state.Gamepad.wButtons & 0xc00) << 2;
		// XWA can map only 12 buttons, so map dpad to POV
		pji->dwPOV = povmap[state.Gamepad.wButtons & 15];
```

This will remove the throttle from the trigger. People might want the right trigger to be fire (as I use it and some other folks) and the Left trigger to be something else other than throttle. Perhaps there can be functionality to combine multiple buttons, but that should be later down the line unless it can implemented smoothly.

I also recommend having two branches, one that is the stable branch and the other the experimental. The stable one should be for the majority of users and may get features from the experimental branch if proven stable. This way a large amount of users will not be affected by these experimental changes.

**Comment by rdoeffinger** [comment]
It's better to post diffs because I can't really see what you changed. In particular I can't see what you mean by "as well as remove the hardware mapping on the left trigger".
Anyway I made it an option.
I don't have the time to maintain 2 branches, plus it only helps if there's enough testers and some way to get the experimental releases to them...
Either way here is the latest code, with the black screen fix and all.
[ddraw.zip](https://github.com/rdoeffinger/xwa_ddraw_d3d11/files/2798672/ddraw.zip)

**Comment by bguthrie1** [comment]
Ah here is what I've changed (please let me know if there is a more effective way)

```C
//pji->dwZpos = state.Gamepad.bRightTrigger;
//pji->dwVpos = state.Gamepad.bLeftTrigger;
```

I've removed the Z and V axis/position mappings from the triggers.

I will take a look at the ddraw you posted.

**Comment by bguthrie1** [comment]
Triggers are good, glad that its defaulted to off. 

There seems to be a flickering issue with the textures though, I'll post in a separate issue.
