### ISSUE TITLE
Crash when 3D hardware is turned on

### ISSUE THREAD

**Issue by bguthrie1** [rdoeffinger/xwa_ddraw_d3d11#7]
A friend of mine is having a crash to desktop when turning on 3D Hardware and going in flight. Its fine when he runs on 16-bit.

Here is the event viewer log of the crash:

![unknown](https://user-images.githubusercontent.com/43460482/51442957-6c0de480-1c97-11e9-95b7-11e1d31e6837.png)

**Comment by rdoeffinger** [comment]
Sorry, I can't reproduce it and the event viewer has far too little data. Unless there's a way to get a debugger backtrace or something like that the chances of finding a fix are fairly slim.

**Comment by rdoeffinger** [comment]
Actually one nugget of information is that "faulting module path" is also XWING95.EXE, so it's not a crash in ddraw.dll itself.
That might mean that checking the compatibility settings might be a good idea, though I am not sure which exact settings should be used.

**Comment by bguthrie1** [comment]
He reinstalled the game and redownloaded the latest ddraw. Not sure what caused the issue but all is good now.
