### ISSUE TITLE
MIPs for X-Wing and TIE Fighter

### ISSUE THREAD

**Issue by testtank400** [rdoeffinger/xwa_ddraw_d3d11#8]
Check your XWAUP PMs, I've found a way to fix the MIPs for X-Wing and TIE Fighter

Before:
![screenshot 998](https://user-images.githubusercontent.com/43460482/51779760-2483c000-20be-11e9-8a3d-9ff249c26d63.png)

After:
![screenshot 999](https://user-images.githubusercontent.com/43460482/51779766-2c436480-20be-11e9-9a79-175b7247262c.png)

**Comment by rdoeffinger** [comment]
Hard to be sure just from the screenshots, but this doesn't look quite right to me.
Do the textures blink/flicker/... when moving? It looks to me like the dll failed to generate the extra mipmap levels. Or maybe it's just my browser doing some bad scaling to the images.

**Comment by bguthrie1** [comment]
No the textures do not blink or flicker.
