### ISSUE TITLE
XWA Map and targeting issues

### ISSUE THREAD

**Issue by bguthrie1** [rdoeffinger/xwa_ddraw_d3d11#9]
There seems to be some weird bug from the latest development of the ddraw (not from 1.5.7) that causes a strange issue with the map:

![image](https://user-images.githubusercontent.com/43460482/51779892-0ec2ca80-20bf-11e9-9032-0c418f7a0a13.png)

Interestingly, if a large ship is targeted this happens:

![image](https://user-images.githubusercontent.com/43460482/51779900-213d0400-20bf-11e9-916f-61bf322f3923.png)

It seems familiar to the 32-bit rendering issue a while back. Did something get reverted or changed?

**Comment by rdoeffinger** [comment]
Yeah, I had a suspicion that a piece of code was removed that was actually needed.
